services:
 
  collection:
    build: 
      context: .
      dockerfile: data_collection/Dockerfile
    environment:
      - BUCKET_NAME=${BUCKET_NAME}
      - DB_HOST=db
      - DB_PASSWORD=${DB_PASSWORD}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    depends_on:
      - postgres_db

  
  retrieval:
    build:
      context: .
      dockerfile: data_retrieval/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db  
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - postgres_db

  
  visualisation:
    build: ./microservices/visualisation
    ports:
      - "8501:8501" 
    environment:
      - API_URL=http://retrieval:8000
    depends_on:
      - retrieval

  
  postgres_db:
    image: postgres:15
    environment:
      - POSTGRES_PASSWORD=testpassword
      - POSTGRES_DB=vulnerability_db
    ports:
      - "5432:5432"