services:
  cisa-scraper:
    build: .
    command: python microservices/data_collection/src/cisa.py

  enricher:
    build: .
    command: python microservices/data_collection/src/enrich.py

  processor:
    build: .
    command: python microservices/data_collection/src/processor.py
  
  reference:
    build: .
    command: python microservices/data_collection/src/reference.py
  
  company_summary:
    build: .
    command: python microservices/data_retrieval/src/company_summary.py
  
  company_vulnerabilities:
    build: .
    command: python microservices/data_retrieval/src/company_vulnerabilities.py

  vulnerability_info:
    build: .
    command: python microservices/data_retrieval/src/vulnerability_info.py
  
  cve_growth:
    build: .
    command: python microservices/data_retrieval/src/cve_growth/cve_growth_lambda.py

  heatmap:
    build: .
    command: python microservices/data_retrieval/src/heatmap/heatmap_lambda.py

  visualiser:
    build: .
    command: python microservices/data_retrieval/src/visualiser/visualiser_lambda.py