import json
import os
import pytest
import datetime 
import boto3
import psycopg2
import requests

BASE_URL = "https://5j1yyqhms4.execute-api.ap-southeast-2.amazonaws.com/"

class AnyString():
    def __eq__(self, value):
        return isinstance(value, str)

# init seed vars
LAMBDA_FUNCTION_NAME = "company_summary_lambda"
CVE_ID = "CVE-2026-99999"
COMPANY_ID = 9999
VULN_NAME = "test vulnerability"
DESC = "test description"
DATE_ADDED = datetime.datetime.strptime("2026-04-01", "%Y-%m-%d").date()
DUE_DATE = datetime.datetime.strptime("2026-04-05", "%Y-%m-%d").date()
CVSS = 9
CVSS_SEVERITY = "TEST_SEVERITY"
EPSS = 0.8
EPSS_PERCENTILE = 0.9
RISK_INDEX = round((float(CVSS) / 10) * 0.6 + float(EPSS) * 0.4, 4)
RISK_RATING = "CRITICAL"
COMPANY_NAME = "test_company_name"

NULL_CVE_ID = "CVE-1111-0000"

CVE_ID_1 = "CVE-2027-9998"
VULN_NAME_1 = "test vulnerability 1"
DESC_1 = "test description 1"
CVSS_1 = 5.2
EPSS_1 = 0.4
RISK_INDEX_1 = round((float(CVSS_1) / 10) * 0.6 + float(EPSS_1) * 0.4, 4)
RISK_RATING_1 = "MEDIUM"

AVG_CVSS = 7.1
AVG_EPSS = 0.6
AVG_RISK_INDEX=0.472
AVG_RISK_RATING = "MEDIUM"

WHITESPACE_NAME = "whitespace company name"



@pytest.fixture(scope="module")
def lambda_client():
    # no need to pass in env variables (aws keys), boto3 does this automatically
    # so when called from staging branch, should have the right access.
    return boto3.client("lambda")

# connect to db
@pytest.fixture(scope="module")
def conn_db():
    conn = None
    DB_PASSWORD = os.environ.get("DB_PASSWORD")
    DB_HOST = os.environ.get("DB_HOST")
    cert_path = os.environ.get("CERT_PATH", "global-bundle.pem")
    print('\nDB_PASSWORD', DB_PASSWORD)

    print('\ndb_host', DB_HOST)
    conn = psycopg2.connect(
            host=DB_HOST,
            port=5432,
            database=os.environ.get("DB_NAME", "postgres"),
            user=os.environ.get("DB_USER", "postgres"),
            password=DB_PASSWORD,
            sslmode="prefer",
            connect_timeout=5,
            sslrootcert=cert_path,
    )
    print('\nconnection succesful')
    yield conn
    conn.close()
            
@pytest.fixture(scope="function")
def seed_whitespace_company(conn_db):
    cur = conn_db.cursor()
    query = """
            INSERT INTO companies (
            company_name, num_vulnerabilities, avg_cvss, 
            avg_epss, risk_index, risk_rating, earliest_vuln_date
        ) VALUES (%s, %s, %s, %s, %s, %s, %s);
    """
    cur.execute(query, (
        WHITESPACE_NAME, 0, 0,
        0, 0, "UNKNOWN", None
    ))

    conn_db.commit()

    yield
    
    delete_company_query = "DELETE FROM companies WHERE id = %s;"
    cur.execute(delete_company_query, (WHITESPACE_NAME,))
    conn_db.commit()


# seed db, this sets up and tears down the vulnerability for every test
@pytest.fixture(scope="function", autouse=True)
def seed_db(conn_db):
    cur = conn_db.cursor()

    # seed company
    insert_company_query = """
        INSERT INTO companies (
            company_name, num_vulnerabilities, avg_cvss, 
            avg_epss, risk_index, risk_rating, earliest_vuln_date
        ) VALUES (%s, %s, %s, %s, %s, %s, %s);
    """
    cur.execute(insert_company_query, (
        COMPANY_NAME, 3, AVG_CVSS,
        AVG_EPSS, AVG_RISK_INDEX, AVG_RISK_RATING, DATE_ADDED
    ))

    conn_db.commit()
    print('succesfully seeded company')

    # get the (autogenerated) serial id
    query = """
        select id from companies c where c.company_name=%s;
    """
    cur.execute(query, (COMPANY_NAME,))
    row = cur.fetchone()
    SERIAL_COMPANY_ID = row
    print('serial company id', SERIAL_COMPANY_ID)

    # seed 2 vulnerabilities
    query = """
        insert into vulnerabilities (cve_id, company_id, vulnerability_name, description,
          date_added, due_date, cvss_score, cvss_severity, epss_score, epss_percentile)
        values (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s);
    """
    cur.execute(query, (CVE_ID, SERIAL_COMPANY_ID, VULN_NAME, DESC, DATE_ADDED, DUE_DATE, CVSS, CVSS_SEVERITY, EPSS, EPSS_PERCENTILE,))
    
    query = """
        insert into vulnerabilities (cve_id, company_id, vulnerability_name, description,
          date_added, due_date, cvss_score, cvss_severity, epss_score, epss_percentile)
        values (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s);
    """
    cur.execute(query, (CVE_ID_1, SERIAL_COMPANY_ID, VULN_NAME_1, DESC_1, DATE_ADDED, DUE_DATE, CVSS_1, CVSS_SEVERITY, EPSS_1, EPSS_PERCENTILE,))

    # vuln with missing cvss/epss info
    query = """
        INSERT INTO vulnerabilities (cve_id, company_id, vulnerability_name, description,
          date_added, due_date, cvss_score, cvss_severity, epss_score, epss_percentile)
        VALUES (%s, %s, %s, %s, %s, %s, NULL, NULL, NULL, NULL);
    """
    cur.execute(query, (
        NULL_CVE_ID, SERIAL_COMPANY_ID, "test_ null vuln", DESC, DATE_ADDED, DUE_DATE
    ))
    print('added seed successfully')
    conn_db.commit()

    yield

    delete_query = "DELETE FROM vulnerabilities WHERE cve_id = %s;"
    cur.execute(delete_query, (CVE_ID,))

    delete_query = "DELETE FROM vulnerabilities WHERE cve_id = %s;"
    cur.execute(delete_query, (CVE_ID_1,))

    delete_query = "DELETE FROM vulnerabilities WHERE cve_id = %s;"
    cur.execute(delete_query, (NULL_CVE_ID,))

    delete_company_query = "DELETE FROM companies WHERE id = %s;"
    cur.execute(delete_company_query, (COMPANY_ID,))

    conn_db.commit()
    print('teardown successful')

    cur.close()

# INTEGRATION TESTS
def test_company_summary_success(lambda_client):
    event = {
        "pathParameters": {
            "company_name": COMPANY_NAME
        }
    }
    
    response = lambda_client.invoke(
        FunctionName=LAMBDA_FUNCTION_NAME,
        InvocationType="RequestResponse",
        Payload=json.dumps(event)
    )
    
    response = json.loads(response["Payload"].read().decode("utf-8"))
    print('\nresponse is ', response)
    body = json.loads(response["body"])
    expected_response_body = {
        "company": COMPANY_NAME,
        "cve_count": 3,
        "avg_epss": AVG_EPSS,
        "avg_cvss": AVG_CVSS,
        "risk_index": AVG_RISK_INDEX,
        "risk_rating": AVG_RISK_RATING,
        "time": {
            "timestamp": AnyString(),
            "timezone": AnyString()
        }
    }
    
    assert response["statusCode"] == 200
    assert body == expected_response_body

def test_company_not_found(lambda_client):
    company_not_found = "diddybludcompany"
    event = {
        "pathParameters": {
            "company_name": company_not_found
        }
    }

    response = lambda_client.invoke(
        FunctionName=LAMBDA_FUNCTION_NAME,
        InvocationType="RequestResponse",
        Payload=json.dumps(event)
    )
    
    response = json.loads(response["Payload"].read().decode("utf-8"))
    body = json.loads(response["body"])
    
    assert response["statusCode"] == 404
    assert body == {"error": "Company not found"}

COMPANY_SUMMARY_URL = BASE_URL + "/v1/companies"

# E2E TESTS
def test_endpoint_success():
    response = requests.get(f"{COMPANY_SUMMARY_URL}/{COMPANY_NAME}", timeout=30)
    expected_response_body = {
        "company": COMPANY_NAME,
        "cve_count": 3,
        "avg_epss": AVG_EPSS,
        "avg_cvss": AVG_CVSS,
        "risk_index": AVG_RISK_INDEX,
        "risk_rating": AVG_RISK_RATING,
        "time": {
            "timestamp": AnyString(),
            "timezone": AnyString()
        }
    }
    
    assert response.status_code == 200
    assert response.json() == expected_response_body