import json
import os
import pytest
import datetime 
import boto3
import psycopg2
import requests
from vars import BASE_URL

class AnyString():
    def __eq__(self, value):
        return isinstance(value, str)

# init seed vars
LAMBDA_FUNCTION_NAME = "vuln_info_lambda"
CVE_ID = "CVE-2026-99999"
COMPANY_ID = 9999
VULN_NAME = "test vulnerability"
DESC = "test description"
DATE_ADDED = datetime.datetime.strptime("2026-04-01", "%Y-%m-%d").date()
DUE_DATE = datetime.datetime.strptime("2026-04-05", "%Y-%m-%d").date()
CVSS = 9
CVSS_SEVERITY = "TEST_SEVERITY"
EPSS = 0.8
EPSS_PERCENTILE = 0.9
RISK_INDEX = round((float(CVSS) / 10) * 0.6 + float(EPSS) * 0.4, 4)
RISK_RATING = "CRITICAL"
COMPANY_NAME = "test_company_name"

NULL_CVE_ID = "CVE-1111-0000"



@pytest.fixture(scope="module")
def lambda_client():
    # no need to pass in env variables (aws keys), boto3 does this automatically
    # so when called from staging branch, should have the right access.
    return boto3.client("lambda")

# connect to db
@pytest.fixture(scope="module")
def conn_db():
    conn = None
    DB_PASSWORD = os.environ.get("DB_PASSWORD")
    DB_HOST = os.environ.get("DB_HOST")
    cert_path = os.environ.get("CERT_PATH", "global-bundle.pem")
    print('\nDB_PASSWORD', DB_PASSWORD)

    print('\ndb_host', DB_HOST)
    conn = psycopg2.connect(
            host=DB_HOST,
            port=5432,
            database=os.environ.get("DB_NAME", "postgres"),
            user=os.environ.get("DB_USER", "postgres"),
            password=DB_PASSWORD,
            sslmode="prefer",
            connect_timeout=5,
            sslrootcert=cert_path,
    )
    print('\nconnection succesful')
    yield conn
    conn.close()
            

# seed db, this sets up and tears down the vulnerability for every test
@pytest.fixture(scope="function", autouse=True)
def seed_db(conn_db):
    cur = conn_db.cursor()

    # seed company
    insert_company_query = """
        INSERT INTO companies (
            company_name, num_vulnerabilities, avg_cvss, 
            avg_epss, risk_index, risk_rating, earliest_vuln_date
        ) VALUES (%s, %s, %s, %s, %s, %s, %s);
    """
    cur.execute(insert_company_query, (
        COMPANY_NAME, 1, CVSS,
        EPSS, RISK_INDEX, RISK_RATING, DATE_ADDED
    ))

    conn_db.commit()
    print('succesfully seeded company')

    # get the (autogenerated) serial id
    query = """
        select id from companies c where c.company_name=%s;
    """
    cur.execute(query, (COMPANY_NAME,))
    row = cur.fetchone()
    SERIAL_COMPANY_ID = row
    print('serial company id', SERIAL_COMPANY_ID)

    # seed vulnerability
    query = """
        insert into vulnerabilities (cve_id, company_id, vulnerability_name, description,
          date_added, due_date, cvss_score, cvss_severity, epss_score, epss_percentile)
        values (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s);
    """
    cur.execute(query, (CVE_ID, SERIAL_COMPANY_ID, VULN_NAME, DESC, DATE_ADDED, DUE_DATE, CVSS, CVSS_SEVERITY, EPSS, EPSS_PERCENTILE,))
    conn_db.commit()
    print('added seed successfully')

    # vuln with missing cvss/epss info
    query = """
        INSERT INTO vulnerabilities (cve_id, company_id, vulnerability_name, description,
          date_added, due_date, cvss_score, cvss_severity, epss_score, epss_percentile)
        VALUES (%s, %s, %s, %s, %s, %s, NULL, NULL, NULL, NULL);
    """
    cur.execute(query, (
        NULL_CVE_ID, SERIAL_COMPANY_ID, "test_ null vuln", DESC, DATE_ADDED, DUE_DATE
    ))
    conn_db.commit()

    yield

    delete_query = "DELETE FROM vulnerabilities WHERE cve_id = %s;"
    cur.execute(delete_query, (CVE_ID,))

    delete_query = "DELETE FROM vulnerabilities WHERE cve_id = %s;"
    cur.execute(delete_query, (NULL_CVE_ID,))

    delete_company_query = "DELETE FROM companies WHERE id = %s;"
    cur.execute(delete_company_query, (COMPANY_ID,))

    conn_db.commit()
    print('teardown successful')

    cur.close()

# INTEGRATION TESTS
# test lambda retrieving from rds
def test_vuln_retrieval_success(lambda_client):
    event = {
        "pathParameters": {
            "cve_id": CVE_ID
        }
    }
    
    response = lambda_client.invoke(
        FunctionName=LAMBDA_FUNCTION_NAME,
        InvocationType="RequestResponse",
        Payload=json.dumps(event)
    )
    
    response = json.loads(response["Payload"].read().decode("utf-8"))
    print('\nresponse is ', response)
    body = json.loads(response["body"])
    expected_response_body = {
        "cve_id": CVE_ID,
        "name": VULN_NAME,
        "description": DESC,
        "dateAdded": str(DATE_ADDED),
        "dueDate": str(DUE_DATE),
        "cvss": CVSS,
        "epss": EPSS,
        "risk_index": RISK_INDEX,
        "risk_rating": RISK_RATING,
        "time": {
            "timestamp": AnyString(),
            "timezone": AnyString()
        }
    }
    
    assert response["statusCode"] == 200
    assert body == expected_response_body

def test_cve_not_found(lambda_client):
    cve_not_found = "CVE-0000-12930"
    event = {
        "pathParameters": {
            "cve_id": cve_not_found
        }
    }

    response = lambda_client.invoke(
        FunctionName=LAMBDA_FUNCTION_NAME,
        InvocationType="RequestResponse",
        Payload=json.dumps(event)
    )
    
    response = json.loads(response["Payload"].read().decode("utf-8"))
    body = json.loads(response["body"])
    
    assert response["statusCode"] == 404
    assert body == {"error": "CVE not found"}

def test_no_param_defined(lambda_client):

    response = lambda_client.invoke(
        FunctionName=LAMBDA_FUNCTION_NAME,
        InvocationType="RequestResponse",
        Payload=json.dumps({})
    )
    
    response = json.loads(response["Payload"].read().decode("utf-8"))
    body = json.loads(response["body"])
    
    assert response["statusCode"] == 400
    assert body == {"error": "cve_id is required in the URL"}

def test_null_cvss_epss(lambda_client):
    event = {
        "pathParameters": {
            "cve_id": NULL_CVE_ID
        }
    }
    
    response = lambda_client.invoke(
        FunctionName=LAMBDA_FUNCTION_NAME,
        InvocationType="RequestResponse",
        Payload=json.dumps(event)
    )
    
    response_payload = json.loads(response["Payload"].read().decode("utf-8"))
    body = json.loads(response_payload["body"])
    
    assert response_payload["statusCode"] == 200
    
    # check that null cvss and epss are handled correctly
    assert body["cvss"] == -1.0
    assert body["epss"] == -1.0
    assert body["risk_index"] == 0
    assert body["risk_rating"] == "UNKNOWN"

RETRIEVAL_URL = BASE_URL + "/v1/vulnerabilities"

# e2e? tests - calling api
def test_endpoint_success():
    response = requests.get(f"{RETRIEVAL_URL}/{CVE_ID}", timeout=30)
    expected_response_body = {
        "cve_id": CVE_ID,
        "name": VULN_NAME,
        "description": DESC,
        "dateAdded": str(DATE_ADDED),
        "dueDate": str(DUE_DATE),
        "cvss": CVSS,
        "epss": EPSS,
        "risk_index": RISK_INDEX,
        "risk_rating": RISK_RATING,
        "time": {
            "timestamp": AnyString(),
            "timezone": AnyString()
        }
    }
    assert response.status_code == 200
    assert response.json() == expected_response_body

def test_endpoint_no_cve_found():
    response = requests.get(f"{RETRIEVAL_URL}/CVE-1230-0123", timeout=30)

    assert response.status_code == 404
    assert response.json() == {"error": "CVE not found"}

def test_endpoint_wrong_cve_format():
    response = requests.get(f"{RETRIEVAL_URL}/CVE-", timeout=30)

    assert response.status_code == 400
    assert response.json() == {"error": "Invalid CVE ID format"}